apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: rbot-tls
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: chadc@linux.com
    privateKeySecretRef:
      name: rbot-tls
    solvers:
      - http01:
          ingress:
            class: azure/application-gateway
            podTemplate:
              spec:
                nodeSelector:
                  'kubernetes.io/os': linux
